import path from 'node:path';import {fileURLToPath} from 'node:url';
import {ConfigStore} from './config.mjs';import {AccountsStore,validateUid,AccountsError} from './accounts.mjs';import {HoyolabClient} from './hoyolab.mjs';import {PublicData,formatShowcase,formatWiki,formatPackages} from './public.mjs';import {GachaStore,formatGacha} from './gacha.mjs';import {Subscriptions} from './subscriptions.mjs';
import {SecretStore,SecretError} from './secrets.mjs';
import {MysQrLogin} from './mys-qr.mjs';
import {ManualVerification} from './manual-verification.mjs';
import {PackageHistory,formatHistory} from './package-history.mjs';
import {MiyousheCoinClient} from './miyoushe-coins.mjs';
export const rootDefault=fileURLToPath(new URL('../',import.meta.url));
export class Teyvat{
  constructor(root=rootDefault,options={}){this.root=root;this.options=options;this.config=new ConfigStore(root);const c=this.config.init();this.accounts=new AccountsStore(root,{key:c.credentialsKey});this.secrets=new SecretStore(root,c.credentialsKey);this.mys=new HoyolabClient({fetch:options.fetch,timeoutMs:c.timeoutMs});this.verification=new ManualVerification({mys:this.mys,prefix:c.prefix,now:options.now});this.login=new MysQrLogin(root,{accounts:this.accounts,mys:this.mys,fetch:options.fetch,timeoutMs:c.timeoutMs,...(options.qr?{encodeQr:options.qr}:{})});this.qrSessions=new Map();this.public=new PublicData(root,{fetch:options.fetch,timeoutMs:c.timeoutMs,cacheSeconds:c.cacheSeconds});this.gacha=new GachaStore(root);this.subscriptions=new Subscriptions(root,{accounts:this.accounts,mys:this.mys,publicData:this.public,send:options.send,config:this.config,now:options.now})}
  help(){const p=this.config.read().prefix;return ['提瓦特助手 0.1.0 · 国服优先',`${p}扫码登录 [UID] / 扫码状态 / 取消扫码（私聊，米游社APP）`,`${p}绑定 UID / 账户 / 切换 UID / 解绑 UID / 登录说明`,`${p}安全验证 / 提交验证 页面生成的回执 / 取消验证（仅本人私聊）`,`${p}展柜 [UID] / 便笺 / 树脂 / 深渊 / 剧诗 / 危战 / 个人资料 / 角色列表 / 养成 角色ID`,`${p}米游币 / 米游币任务（本人私聊，只读）`,`${p}活动日历 / 七圣召唤 / 七圣牌组 / 七圣卡牌 / 养成计算 JSON`,`${p}原石札记 [月份] / 尘歌壶方案 模数 / 家具计算 JSON`,`${p}角色 名称 / 武器 名称 / 圣遗物 名称 / 材料 名称`,`${p}版本 / 预下载 / 版本历史 / 安装包 / 预下载包 / 包体历史 / 版本数据 [版本号] / 更新版本数据（主人）`,`${p}祈愿导入 JSON / 祈愿分析 / 祈愿导出（私人记录只私聊）`,`${p}树脂提醒 开/关 [阈值] / 版本推送 开/关 / 订阅列表`,`${p}墨安绑定 API-Key / 墨安分析 / 墨安记录 / 云端拉取 / 云端导出 / 云端上传 / 云链接验证 / 云链接导入（服务需配置）`,`${p}功能 / 状态`, '深度图片、伤害与统计用原命令：#雷神面板、#更新面板、#深渊配队、#持有率、#队伍伤害等。','所有登录账号统一AES加密保存；原生明文绑定入口停用。'].join('\n')}
  async handle(event){const c=this.config.read();const text=String(event.text??event.msg??'').trim();if(!text.startsWith(c.prefix)||!c.enabled)return {handled:false};const owner=String(event.owner||event.user_id||'');if(!owner)return {handled:true,text:'缺少用户身份，无法读取账户。'};const privateChat=!event.group_id&&event.privateChat!==false;const body=text.slice(c.prefix.length).trim();const cmd=body.split(/\s+/)[0]||'帮助';const arg=body.slice(cmd.length).trim();try{const result=await this.command(cmd,arg,{owner,privateChat,isMaster:event.isMaster===true,botId:String(event.self_id||event.bot?.uin||''),groupId:event.group_id?String(event.group_id):null});if(result.file||result.image)return {handled:true,...result};return {handled:true,text:String(result.text??result).slice(0,c.maxReplyChars)}}catch(error){return {handled:true,text:error instanceof AccountsError||error instanceof SecretError?error.message:'操作未完成：参数无效、授权不足或数据接口暂不可用。请用 '+c.prefix+'状态 检查配置。'}}}
  async command(cmd,arg,ctx){const a=()=>{const account=this.accounts.selected(ctx.owner);if(!account)throw new AccountsError('not_bound','请先私聊 #原神扫码登录，或 #原神绑定 UID。');return account};const authQuery=async(kind,params={})=>{const account=a();if(!account.hasCookie)return '请先私聊授权当前UID的米游社Cookie；只绑定UID无法查看个人数据。';const result=await this.mys.query(kind,account,params);if(!result.ok)return result.message;const text=this.formatRecord(cmd,result.data);return ctx.privateChat&&text.length>this.config.read().maxReplyChars?{text:'完整个人记录已导出JSON。',file:{name:'Genshin-'+kind.replace(/[^a-zA-Z0-9_-]/g,'-')+'.json',data:JSON.stringify(result.data,null,2)}}:text};
    if(cmd==='帮助')return this.help();
    if(['安全验证','提交验证','取消验证'].includes(cmd)){if(!ctx.privateChat)return '安全验证和回执只允许本人私聊。';if(cmd==='取消验证')return this.verification.cancel(ctx.owner);return cmd==='安全验证'?this.verification.start(ctx.owner,a(),{privateChat:true}):this.verification.finish(ctx.owner,arg,a(),{privateChat:true});}
    if(cmd==='登录说明')return '国服请私聊 #原神扫码登录 [可选UID]，用米游社APP扫一扫，在官方页面确认。验证本人国服角色后AES加密保存，可绑定多个账号并用 #原神切换 UID 切换。不接受密码；Cookie手工授权仍可私聊 #原神绑定Cookie UID Cookie。';
    if(cmd==='登录'||cmd==='扫码登录'){if(!ctx.privateChat)return '米游社扫码登录仅允许私聊。';const r=await this.login.start(ctx.owner,{privateChat:true,...(arg?{uid:arg}:{})});if(!r.ok)return r.message;this.qrSessions.set(ctx.owner,r.sessionId);return {image:r.qrPng,qrSession:r.sessionId,text:'请用米游社APP扫一扫此二维码，在官方页面确认。\nbot会检查授权状态；也可 #原神扫码状态。二维码勿转发。角色归属验证通过后，所有账号凭据仅AES加密保存。'}}
    if(cmd==='扫码状态'||cmd==='取消扫码'){if(!ctx.privateChat)return '扫码操作仅允许私聊。';const id=this.qrSessions.get(ctx.owner);if(!id)return '当前没有待确认扫码，请私聊 #原神扫码登录。';const r=cmd==='取消扫码'?this.login.cancel(ctx.owner,id,{privateChat:true}):await this.login.poll(ctx.owner,id,{privateChat:true});if(!r.ok)return r.message;if(r.status==='Confirmed')return '米游社授权及本人国服角色已验证，AES加密保存：'+r.accounts.map(a=>a.uid).join('、')+'。';return r.status==='Scanned'?'已扫描，请在米游社APP确认授权。':r.status==='Cancelled'?'已取消扫码登录。':'等待米游社APP扫码确认。'}
    if(cmd==='墨安绑定'){if(!ctx.privateChat)return 'API Key只可在私聊或实例配置提交。';this.secrets.set(ctx.owner,arg);return '已加密保存本人墨安API Key；服务连接需管理员配置有效HTTPS接口，不代表云端登录成功。'}
    if(cmd==='墨安解绑'){if(!ctx.privateChat)return 'API Key解绑请私聊。';this.secrets.set(ctx.owner,null);return '已删除本bot保存的本人墨安API Key。'}
    if(['墨安分析','墨安记录','云端导出','云端拉取','云端上传','云端批量上传','云链接验证','云链接导入'].includes(cmd))return this.cloudCommand(cmd,arg,ctx);
    if(cmd==='绑定'){const data=this.accounts.bind(ctx.owner,{uid:arg});return '已绑定UID '+data.uid+'（'+data.server+'）；这只建立查询目标，尚未登录米游社/HoYoLAB。'}
    if(cmd==='绑定Cookie'){if(!ctx.privateChat)return 'Cookie只能在私聊提交；请立即撤回含凭据的群消息。';if(!this.config.read().allowCookieInPrivate)return '管理员已关闭私聊Cookie绑定。';const match=arg.match(/^(\d{9,10})\s+(.+)$/s);if(!match)return '用法：#原神绑定Cookie UID Cookie（仅私聊）。';const region=validateUid(match[1]).region;const roles=await this.mys.roles(match[2],region);if(!roles.ok)return roles.message;const role=roles.data.find(x=>x.uid===match[1]);if(!role)return '当前授权不拥有该UID，绑定已拒绝。';this.accounts.bind(ctx.owner,{uid:role.uid,region:role.region,server:role.server,cookie:match[2],label:role.nickname,privateChat:true});return '已验证并加密保存UID '+role.uid+' 的米游社/HoYoLAB授权。';}
    if(cmd==='账户'){const rows=this.accounts.list(ctx.owner);return rows.map(x=>`${x.uid} ${x.label||''} ${x.server} ${x.hasCookie?'已授权':'仅UID'}`).join('\n')||'尚未绑定账户。'}
    if(cmd==='切换'){this.verification.cancel(ctx.owner);this.accounts.select(ctx.owner,arg);return '已切换至UID '+arg}
    if(cmd==='解绑'){this.verification.cancel(ctx.owner);this.accounts.remove(ctx.owner,arg||a().uid);return '已删除本bot保存的该账户授权与绑定；米游社授权本身需在官方账号中心管理。'}
    if(cmd==='展柜'||cmd==='面板')return formatShowcase(await this.public.showcase(arg||a().uid));
    if(cmd==='角色'||cmd==='武器'||cmd==='圣遗物'||cmd==='材料')return formatWiki(this.public.wiki({'角色':'characters','武器':'weapons','圣遗物':'artifacts','材料':'materials'}[cmd],arg));
    if(cmd==='版本'||cmd==='预下载'){const v=await this.public.version();return `国服原神PC版本 ${v.current||'未公布'}\n预下载 ${v.preDownload||'尚未开放'}\n查询时间 ${v.time}\n来源：米哈游HoYoPlay启动器。`}
    if(cmd==='安装包'||cmd==='包体'||cmd==='预下载包')return formatPackages(await this.public.packages(cmd==='预下载包'?'pre':'main'));
    if(cmd==='包体历史')return JSON.stringify(this.public.packageHistory(arg==='预下载'?'pre':undefined),null,2)||'还没有包体变化观察。';
    if(cmd==='版本历史')return this.public.versionHistory().map(v=>`${v.time} · ${v.current} · 预下载 ${v.preDownload||'无'}`).join('\n')||'还没有版本观察记录；先查询一次版本。';
    if(cmd==='版本数据'){const history=new PackageHistory(this.root,{fetch:this.options.fetch,timeoutMs:this.config.read().timeoutMs});const value=history.list(arg||undefined);const output=formatHistory(value);if(output.length<=this.config.read().maxReplyChars)return output;if(!ctx.privateChat)return `资料库收录正式版本 ${value.main.length} 条、预下载 ${value.pre.length} 条。请私聊 ${this.config.read().prefix}版本数据 获取完整列表，或加版本号查询（如 7.1.0）。`;return {text:'完整历史列表已生成文本；这是 GamePush 作者记录，不等于当前启动器统计。',file:{name:'Genshin-Package-History.txt',data:output}};}
    if(cmd==='更新版本数据'){if(!ctx.isMaster)return '版本资料同步仅允许机器人主人操作。';const result=await new PackageHistory(this.root,{fetch:this.options.fetch,timeoutMs:this.config.read().timeoutMs}).update();return `原神历史资料同步完成，新增 ${result.added} 条，保留原有冲突记录 ${result.conflicts} 条。来源：GamePush 作者公开数据库。`;}
    if(cmd==='便笺'||cmd==='树脂'||cmd==='体力')return authQuery('dailyNote');if(cmd==='深渊')return authQuery('spiralAbyss',{schedule_type:arg==='上期'?2:1});if(cmd==='剧诗'||cmd==='幻想真境')return authQuery('role_combat');if(cmd==='角色列表')return authQuery('character');if(cmd==='养成')return arg?authQuery('detail',{avatar_id:Number(arg)}):'用法：'+this.config.read().prefix+'养成 角色ID（例：10000002）；角色ID可从角色列表查看。';
    if(cmd==='米游币'||cmd==='米游币任务'){if(!ctx.privateChat)return '米游币余额和任务状态仅允许本人私聊查询。';const account=a();const client=new MiyousheCoinClient({fetch:this.options.fetch,timeoutMs:this.config.read().timeoutMs});const r=await client[cmd==='米游币'?'balance':'missions'](account);if(!r.ok)return r.message;if(cmd==='米游币')return `米游币余额：${r.data.points}\n来源：米游社官方，只读查询。`;const d=r.data;const output=[`官方任务总积分（total_points）：${d.total_points}`,`已领取积分（already_received_points）：${d.already_received_points}`,`今日总积分（today_total_points）：${d.today_total_points}`,...d.states.map(s=>`任务 ${s.mission_id}：进度 ${s.process??'未返回'}；奖励${s.is_get_award===true?'已领取':s.is_get_award===false?'未领取':'状态未返回'}`),'只查询官方状态；本插件不执行签到、点赞、分享或兑换。'].join('\n');return output.length>this.config.read().maxReplyChars?{text:'完整米游币任务状态已生成文本（只读）。',file:{name:'Miyoushe-Mission-State.txt',data:output}}:output;}
    if(cmd==='危战'||cmd==='幽境')return authQuery('hard_challenge');if(cmd==='个人资料')return authQuery('index');if(cmd==='活动日历')return authQuery('act_calendar');if(cmd==='七圣召唤')return authQuery('gcg/basicInfo');if(cmd==='养成计算'){let params;try{params=JSON.parse(arg)}catch{return '用法：#原神养成计算 JSON（avatar_id、avatar_level_current、avatar_level_target，其他参数见API文档）。'}return authQuery('compute',params)}
    if(cmd==='原石札记'||cmd==='札记')return authQuery('ledger',arg?{month:Number(arg)}:{});
    if(cmd==='尘歌壶方案')return authQuery('blueprint',{share_code:arg});
    if(cmd==='家具计算'){let params;try{params=JSON.parse(arg)}catch{return '用法：#原神家具计算 {"list":[{"id":家具ID,"cnt":数量}]}';}return authQuery('blueprintCompute',params)}
    if(cmd==='七圣牌组')return authQuery('deckList');if(cmd==='七圣卡牌')return authQuery('tcgCards');
    if(cmd==='树脂提醒'||cmd==='版本推送'){const kind=cmd==='树脂提醒'?'resin':'version';const parts=arg.split(/\s+/);if(!['开','关'].includes(parts[0]))return '用法：'+this.config.read().prefix+cmd+' 开/关'+(kind==='resin'?' [树脂阈值]':'');this.subscriptions.set(ctx.owner,{kind,enabled:parts[0]==='开',botId:ctx.botId,groupId:ctx.groupId,...(kind==='resin'&&parts[1]?{threshold:Number(parts[1])}:{})});return cmd+(parts[0]==='开'?'订阅已开启；尚无授权或总开关关闭时不会执行。':'订阅已关闭。')}
    if(cmd==='订阅列表')return JSON.stringify(this.subscriptions.list(ctx.owner),null,2);
    if(cmd==='祈愿分析'){if(!ctx.privateChat)return '本人祈愿记录请在私聊分析。';return formatGacha(this.gacha.analyze(ctx.owner,a().uid));}if(cmd==='祈愿导入'){if(!ctx.privateChat)return '祈愿导入请使用私聊或本地CLI。';const r=this.gacha.import(ctx.owner,a().uid,arg);return `已导入 ${r.imported} 条，去重后共 ${r.total} 条。`}
    if(cmd==='祈愿导出'){if(!ctx.privateChat)return '祈愿记录包含个人游戏信息，请私聊导出。';return {file:{name:'UIGF-'+a().uid+'.json',data:JSON.stringify(this.gacha.export(ctx.owner,a().uid),null,2)}}}
    if(cmd==='状态')return '提瓦特助手核心运行\n'+JSON.stringify({adapter:this.config.read().adapter,region:this.config.read().region,accounts:this.accounts.list(ctx.owner).length,providers:this.nativeStatus||Object.fromEntries(Object.entries(this.config.read().providers).map(([key,enabled])=>[key,enabled?'尚未检查加载':'disabled']))},null,2);
    if(cmd==='功能')return '独立核心已实现账户隔离、AES加密授权、公开展柜、个人记录请求、原神资料、正式/预下载资源包体、UIGF多版本导入/导出/分析、米游币只读查询及用户订阅的提醒。\n墨安原神协议已实现，需可用HTTPS服务和本人Key方能启用。复杂面板、伤害模拟和榜单由外部原神模块提供，加载状态可查。完整参考功能差异与账号待验收项见 docs/FEATURES.md。';
    return '没有识别该命令；发送 '+this.config.read().prefix+'帮助 查看可用功能。';
  }
  formatRecord(kind,data){if(kind==='树脂'||kind==='体力'||kind==='便笺'){return [`树脂 ${data.current_resin??'?'} / ${data.max_resin??'?'}`,`回满剩余 ${Math.ceil(Number(data.resin_recovery_time||0)/60)} 分钟`,`每日委托 ${data.finished_task_num??'?'} / ${data.total_task_num??'?'}`,`洞天宝钱 ${data.current_home_coin??'?'} / ${data.max_home_coin??'?'}`,`周本折扣 ${data.remain_resin_discount_num??'?'} / ${data.resin_discount_num_limit??'?'}`,`探索派遣 ${(data.expeditions||[]).length} 队`,`参量质变仪：${data.transformer?.obtained?(data.transformer?.recovery_time?.reached?'可使用':'恢复中'):'未取得'}`].join('\n')}return JSON.stringify(data,null,2)}
  async cloudCommand(cmd,arg,ctx){
    if(!ctx.privateChat)return '云端记录和Key操作只允许本人私聊。';
    const c=this.config.read();if(!c.providers.moan||!c.moan.baseUrl)return '墨安服务尚未连接：管理员需配置可用HTTPS API并启用providers.moan。当前发现的明文HTTP默认接口不发送凭据。';
    const account=this.accounts.selected(ctx.owner);if(!account)return '请先绑定自己的原神UID。';if(account.region!=='cn')return '当前墨安协议仅支持已核对的国服hk4e_cn。';
    const key=this.secrets.get(ctx.owner)||(c.moan.mode==='shared'?c.moan.key:'');
    if(!key&&!['墨安分析','墨安记录'].includes(cmd))return '请私聊 #原神墨安绑定 API-Key。';
    const {CloudClient}=await import('./cloud.mjs');const client=new CloudClient({baseUrl:c.moan.baseUrl,key,fetch:this.options.fetch,timeoutMs:c.timeoutMs});
    if(cmd==='墨安分析'||cmd==='墨安记录')return JSON.stringify(await client[cmd==='墨安分析'?'analysis':'query'](account.uid),null,2);
    if(cmd==='云端导出'||cmd==='云端拉取'){const result=await client.export(account.uid,{format:arg==='v22'?'v22':'v42'});const payload=result.data?.uigf??result.data?.json??result.data?.records??result.data;const data=typeof payload==='string'?payload:JSON.stringify(payload);if(cmd==='云端拉取'){const r=this.gacha.import(ctx.owner,account.uid,data);return '云端记录已验证UID并写入本人本地库，共 '+r.total+' 条。'}return {file:{name:'Cloud-UIGF-'+account.uid+'.json',data},text:'已生成本人云端祈愿文件。'}}
    if(cmd==='云链接验证')return JSON.stringify(await client.verifyLink(arg,account.uid),null,2);
    if(!c.moan.allowCloudUpload)return '管理员未开启云端上传；开启moan.allowCloudUpload后，本人须明确发送上传或云链接导入命令。';
    if(cmd==='云链接导入'){const r=await client.importLink(arg,account.uid);return '云端已返回本人原神链接导入结果：'+JSON.stringify(r)}
    const accounts=cmd==='云端批量上传'?this.accounts.list(ctx.owner).filter(a=>a.region==='cn'):[account];const rows=[];
    for(const a of accounts){const data=this.gacha.export(ctx.owner,a.uid);const records=data.hk4e?.find(x=>String(x.uid)===a.uid)?.list||data.list||[];if(!records.length){rows.push(a.uid+'：无本地记录，跳过');continue}await client.upload(a.uid,records);rows.push(a.uid+'：服务器已接收上传（'+records.length+'条）')}
    return rows.join('\n');
  }
}
