import fs from 'node:fs';import path from 'node:path';import {randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';import {atomic} from './config.mjs';
const aad=Buffer.from('Teyvat-Plugin/cloud-keys/v1');
export class SecretError extends Error{}
export class SecretStore{
  constructor(root,key){if(!/^[a-f0-9]{64}$/i.test(String(key)))throw new SecretError('凭据加密密钥不可用');this.key=Buffer.from(key,'hex');this.file=path.join(root,'data/cloud-keys.enc.json')}
  owner(owner){const s=String(owner);if(!/^[1-9]\d{4,14}$/.test(s))throw new SecretError('有效QQ身份必需');return s}
  read(){if(!fs.existsSync(this.file))return {};try{const stat=fs.lstatSync(this.file);if(stat.isSymbolicLink()||stat.size>1048576)throw new Error();const e=JSON.parse(fs.readFileSync(this.file,'utf8'));if(e.version!==1)throw new Error();const d=createDecipheriv('aes-256-gcm',this.key,Buffer.from(e.iv,'base64'));d.setAAD(aad);d.setAuthTag(Buffer.from(e.tag,'base64'));const raw=Buffer.concat([d.update(Buffer.from(e.data,'base64')),d.final()]);const v=JSON.parse(raw.toString('utf8'));raw.fill(0);if(!v||Array.isArray(v)||typeof v!=='object')throw new Error();return v}catch{throw new SecretError('云端密钥解密失败；请保留原文件与加密密钥。')}}
  get(owner){return this.read()[this.owner(owner)]||''}
  set(owner,value){const id=this.owner(owner);if(value!==null&&(typeof value!=='string'||!value||value.length>4096||!/^[\x21-\x7e]+$/.test(value)))throw new SecretError('API Key格式无效，不接受密码或多行内容。');fs.mkdirSync(path.dirname(this.file),{recursive:true,mode:0o700});let fd;try{fd=fs.openSync(this.file+'.lock','wx',0o600)}catch{throw new SecretError('凭据文件正在处理，请稍后再试。')}try{const data=this.read();if(value===null)delete data[id];else data[id]=value;const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',this.key,iv);cipher.setAAD(aad);const raw=Buffer.from(JSON.stringify(data));const body=Buffer.concat([cipher.update(raw),cipher.final()]);raw.fill(0);atomic(this.file,{version:1,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:body.toString('base64')})}finally{fs.closeSync(fd);fs.unlinkSync(this.file+'.lock')}}
}
